### ISSUE TITLE
Deprecate `ideascube.yml`

### ISSUE THREAD

**Issue by kelson42** [kiwix/operations#201]
https://download.kiwix.org/library/ideascube.yml

... and all the related tooling because this is not used anymore.

**Comment by rgaudin** [comment]
This is not actionnable. What does _deprecate_ means here?

And you need to be clearer about _not used anymore_: it is still used by kiwix-hotspot which itself has been deprecated.

Here are the stats of the file: 

<img width="1082" alt="Screenshot 2024-06-10 at 07 48 48" src="https://github.com/kiwix/operations/assets/57929/1644dcd5-4fa7-4047-9458-4c97efcf7537">

**Comment by kelson42** [comment]
@rgaudin The only product which uses it is deprecated, so it is a candidate for deprecation. How long would you like to keep it live?

**Comment by rgaudin** [comment]
I don't want to keep it. I just want tickets to be accurate.

**Comment by kelson42** [comment]
@rgaudin I don't understand you. Anyway, please delete everything related to this if none of us wants to keep this.

**Comment by rgaudin** [comment]
Now that's clear! 👍

**Comment by rgaudin** [comment]
I also removed ideascube.yml from https://download.kiwix.org/library/ (copy of the last one in https://download.kiwix.org/archive/hotspot/ideascube_20241101.yml) so that anyone relying on it gets a clear error message (figured emptying it with a comment would lead to weirder bugs)
