### ISSUE TITLE
Create Hotspot demo for ALL preset images

### ISSUE THREAD

**Issue by kelson42** [kiwix/operations#210]
... this will require to switch the demo machine for a machine with 2TB+ hard disk

**Comment by benoit74** [comment]
You mean that you would like to have parallel operations of multiple demos, correct?

BTW, what are **preset** images?

**Comment by rgaudin** [comment]
@benoit74 yes ; sorry we discussed that on the call after your left. That's indeed what we want. The presets are the ready-made images that we currently sell (Preppers, Computer Science, Wikipedia)

**Comment by benoit74** [comment]
No worries, the description was just a bit too blurry so I wanted to be sure about what has been discussed and agreed

**Comment by rgaudin** [comment]
This has been completed in August I think
