### ISSUE TITLE
Should we consider replacing storage k8s node

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#215]
Current situation:
EM-L110X-SATA node from Scaleway (https://www.scaleway.com/en/elastic-metal/lithium/) 
CPU: 1x Intel Xeon E5 1410 v2 ; 4C / 8T - 2,8 GHz
RAM: 96 GB
Disk: 4 x 12 TB HDD (SATA)
Public bandwidth: 1 Gbit/s, unmetered
Price: €131.99/month (VAT **excluded**)

Problem encountered: HDD are slow, especially for OS + ZIM metadata

What we know we need (AFAIK):
- unmetered public bandwidth
- big disks (24T used currently)
- lots of RAM (40G used currently)

Open question: is there a better alternative for same price range?

**Comment by benoit74** [comment]
First SX Hetzner configuration seems significantly more beefy for the same price range: https://www.hetzner.com/dedicated-rootserver/sx65/

CPU: 1x AMD Ryzen™ 7 3700X  (8C / 16T)
RAM: 64G ECC, upgradable to 128G 
Disk: 4 x 22 TB SATA HDD, 2x 1 TB (Gen3) SSD 
Public bandwidth: 1 Gbit/s, unmetered
Price: 123.76€/month (VAT **included**, +29.75€ for 128G ECC instead of 64G and can be done later, when needed, for free)

**Comment by benoit74** [comment]
OVH storage server does not look competitive: https://www.ovhcloud.com/fr/bare-metal/prices/?range=storage

**Comment by benoit74** [comment]
Infomaniak does not seems to propose bare metal

**Comment by rgaudin** [comment]
I think we'll have to use an SSD cache to meet our capacity and budget constraints with performance. I have no experience but I know LVM offers this ; so does bcache. Some filesystems include it as well I think

**Comment by kelson42** [comment]
I have no strong opinion on this and trust both of you to take the smartest solution path.

**Comment by benoit74** [comment]
For the record, the PUE of Hetzner datacenters (found on https://www.hetzner.com/unternehmen/nachhaltigkeit/) is between 1.10 and 1.16 where Scaleway best datacenter is at 1.16 (in DC5, which we use) and average is at 1.37, so no change on this.

**Comment by benoit74** [comment]
@Popolechien can you please open an account on [www.hetzner.com](https://accounts.hetzner.com/signUp) and ask them if they have special program for NGO / open-source so that we are ready, should we confirm the move (which begins to be more and more likely to occur)?

**Comment by benoit74** [comment]
Disk performance suddenly went way better:

![image](https://github.com/kiwix/operations/assets/7102089/14dc3e00-86c8-495a-a176-58b0a2a1917b)

This is visible on the small tests I've ran before as well:

```
root@k8s-storage-node:~# dd if=/dev/zero of=/tmp/test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 10.8679 s, 98.8 MB/s
```

```
root@k8s-storage-node:~# dd if=/dev/zero of=/tmp/test2.img bs=512 count=1000 oflag=dsync
1000+0 records in
1000+0 records out
512000 bytes (512 kB, 500 KiB) copied, 94.0348 s, 5.4 kB/s
```

This is very weird, and does not look related to any ongoing incident in scaleway: https://status.scaleway.com/history

**Comment by benoit74** [comment]
And yesterday I shut down most services on storage node (rsyncd, mirrorbrain, all libraries services, drives) and did not see any change in disk perf.

**Comment by kelson42** [comment]
@benoit74 Canyou please open a ticket at Scaleway to share these facts and complains?

**Comment by benoit74** [comment]
Support ticket opened: https://console.scaleway.com/support/tickets/1444459

(I didn't knew we have phone support 24/7, that's good to know ... not very useful here, they told me I should open a ticket first ... let's see)

**Comment by Popolechien** [comment]
Hetzner got back to me and they don't offer non-profit/FOSS discounts.

**Comment by rgaudin** [comment]
@benoit74 in the [sx65](https://www.hetzner.com/dedicated-rootserver/sx65/) product page, on the sidebar it says `Traffic: 	Unlimited *` with a regular blub on the bottom

> *Traffic usage is unlimited and free of charge.
Please note that our unlimited traffic policy does not apply to servers that have the 10G uplink addon. In this special case, we will charge the usage over 20TB with € 1.19/TB. (The basis for calculation is for outgoing traffic only. Incoming and internal traffic is not calculated.) There is no bandwidth limitation.

Yet, on the features list it says 

> 30.9 TBit total bandwidth 

I'm not sure what this means and I think it should be cleared up.

---

Given the server is OK, I'd propose the following plan (to be discussed live)

- Order one such server
- Setup and test the SSD cache works as expected
- Setup as a new node on our kube, make sure it works as expected (shouldnt be a problem but we've only used servers in SCW DC so far).
- stop zimfarm scheduling
- rsync our data (~12TB)
- implement the kube-level maintenance mode
- stop all services and cron jobs linked to storage (with maintenance mode)
- complete the sync
- reconfigure service as a storage node
- restart services

**Comment by benoit74** [comment]
> 30.9 TBit total bandwidth
> I'm not sure what this means and I think it should be cleared up.
I agree. From what I've checked, it is the total interco bandwidth of the datacenter. TbC before ordering a machine obviously.

**Comment by benoit74** [comment]
Hetzner support:

> Dear client,
Thank you for your message.
All root servers have a dedicated 1 GBit uplink by default and with it unlimited traffic.
https://docs.hetzner.com/robot/general/traffic/
The 30.9 TBit total bandwidth refers to the whole datacenter park
https://www.hetzner.com/unternehmen/rechenzentrum/
There are no limitations from our side regarding K8s nodes.
If you need further assistance, please feel free to contact us.
Kind regards
Simon Albrecht
Hetzner Online GmbH

**Comment by benoit74** [comment]
Answer is now (this has been discussed mostly orally):
- order a SX65 Hetzner box and move `storage` service there => https://github.com/kiwix/operations/issues/226
- ask Scaleway to investigate issues on our machine after service has been moved => https://github.com/kiwix/operations/issues/227

Closing this issue since answer is resolved for now
