### ISSUE TITLE
Customize ZIM_DIRENTLOOKUPCACHE on library generation jobs

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#220]
Set ZIM_DIRENTLOOKUPCACHE=1 on library generation jobs.

This variable controls an operation done right at ZIM opening which consume ZIM_DIRENTLOOKUPCACHE I/Os to read the ZIM and split it.

Setting this to 1 will probably significantly speed-up the library generation job.

This is an interim action until https://github.com/kiwix/operations/issues/215 is answered.

**Comment by kelson42** [comment]
@benoit74 Rapido, et du coup hate de voire le gin quantitatif en rapidité
