### ISSUE TITLE
Investigate potential hardware issue on Scaleway `storage` node

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#227]
Scaleway needs to shutdown the machine to investigate. They can't give us a timeframe or a duration.

We will wait for https://github.com/kiwix/operations/issues/226 to finish and then let them investigate any hardware issue.

We have doubts on this due to https://github.com/kiwix/operations/issues/194 and also variable durations of library generation (significantly longer than few months ago).

**Comment by rgaudin** [comment]
Do you want to conduct additional tests?

**Comment by benoit74** [comment]
Yes I do, will do it on Thursday probably

**Comment by benoit74** [comment]
Tests are not conclusive at all.

I complained at scaleway but they confirm their hardware team did their best and there is nothing left to be done on their side.

I propose to delete the machine, @rgaudin @kelson42 ok for you?

**Comment by rgaudin** [comment]
Good for me

**Comment by benoit74** [comment]
Machine deleted, DNS records cleaned-up.
