### ISSUE TITLE
Logs in grafana are not indexed properly anymore

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#229]
See https://grafana.com/orgs/kiwixorg/tickets/147787

**Comment by benoit74** [comment]
Last status from grafana is not really encouraging:

> I just wanted to provide an update that we are investigating this issue as a potential bug. As soon as we have an update, we will let you know! For now, you'll have to use syntax similar to what we discussed earlier 
{namespace="zimfarm"} | pod =~ `api-deployment-.*`
 >
> to pull all of your logs. Apologies for the change in behavior but we will update you as soon as updates come in.
 >
> I'll place this ticket on hold as we wait further updates so you don't pinged to reply to keep it open. Let us know if you have questions in the meantime!

**Comment by rgaudin** [comment]
Upstream: https://github.com/grafana/loki/issues/13887

This is now the new normal. Closing this issue. Opened #238 with main consequence

**Comment by benoit74** [comment]
I reopen, it is not the right explanation, we are not using empty matchers.

**Comment by benoit74** [comment]
(Grafana support has received a salty message that we really need their help to solve this issue)

**Comment by benoit74** [comment]
We finally got explanation from Grafana support. This is an intended change linked to the introduction of [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/#what-is-structured-metadata). `pod` was previously a label, but it is now a structured metadata, so we have to adapt our queries / dashboards.
