### ISSUE TITLE
Zimfarm dashboard broken

### ISSUE THREAD

**Issue by rgaudin** [kiwix/operations#238]
Due to #229 (itself due to https://github.com/grafana/loki/issues/13887), we need to update all indicators from zimfarm dashboard to use the working syntax

**Comment by benoit74** [comment]
Let's wait for #229 to settle, I reopened this issue

**Comment by benoit74** [comment]
Issue settled, we have to adapt our dashboard, I will do it right now.

**Comment by benoit74** [comment]
Fixed
