### ISSUE TITLE
Revisit CPU requests on `services` node

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#245]
Message when restarting zimfarm API:

```
│   Warning  FailedScheduling   3m32s                  default-scheduler   0/5 nodes are available: 1 Insufficient cpu, 4 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 1  │
│ No preemption victims found for incoming pod, 4 Preemption is not helpful for scheduling.                                                                                                                          │
│   Warning  FailedScheduling   3m20s (x2 over 3m25s)  default-scheduler   0/5 nodes are available: 1 Insufficient cpu, 4 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 1  │
│ No preemption victims found for incoming pod, 4 Preemption is not helpful for scheduling.
```

Obviously it looks to k8s we have no CPU left, probably due to too high requests since node is behaving OK.

**Comment by benoit74** [comment]
Revisited on all nodes and published to prod.
Dashboard added on Grafana: https://kiwixorg.grafana.net/d/fdxs42tegbjlsa/kubernetes-resource-requests
Yearly review added to github workflows.
@rgaudin : you might to want have a look at https://github.com/kiwix/operations/commit/eb20bcf45ccd8e4a226196846fd8d4f5363464ba : I had to specify a deployment strategy for few deployments which cannot be deployed with rolling update, since they use a host port. Wonder why they are not a statefulset, we cannot add replicas.

**Comment by rgaudin** [comment]
@benoit74 cardshop-api-db is not using a hostPort…
All of them should eventually be changed to sts indeed.

**Comment by benoit74** [comment]
OK, then cardshop-api-db only had a concern linked to the fact that we cannot have two running at the same time due to a mongodb lock.
