### ISSUE TITLE
mirrors-qa seems to consume excessive memory for ui-deployment

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#253]
Investigate why mirrors-qa ui-deployment continuously consumes 2G of memory.

https://kiwixorg.grafana.net/a/grafana-k8s-app/navigation/namespace/kiwix-prod/mirrors-qa/deployment/ui-deployment?var-datasource=grafanacloud-kiwixorg-prom&var-loki=grafanacloud-kiwixorg-logs&from=now-7d&to=now

**Comment by rgaudin** [comment]
mirrors-qa UI is not a static website but a metabase instance. It is expected to consume a significant amount of RAM. I am trying to set it to use 1GB instead

**Comment by rgaudin** [comment]
<img width="1115" alt="Screenshot 2024-09-13 at 15 16 20" src="https://github.com/user-attachments/assets/553f6162-610e-4b69-ab31-22a0ab323f4b">
