### ISSUE TITLE
zimit recipes not deleted

### ISSUE THREAD

**Issue by rgaudin** [kiwix/operations#256]
We have a few recipes that were not deleted by frontend.

We need to take a look at reasons for them to be there and delete them manually

<img width="1129" alt="Screenshot 2024-09-16 at 11 32 03" src="https://github.com/user-attachments/assets/2cbb53d9-9b8c-4a54-af5a-244854d6cdfc">

**Comment by benoit74** [comment]
Regarding recent schedules of www.oviles.info: they are here because I did some tests of new zimit-frontend which failed badly and forgot to delete the schedules

Regarding older ones, they are here since quite a long ago, no idea why but we have no more logs obviously.

**Comment by benoit74** [comment]
Cleanup done
