### ISSUE TITLE
Why do we have a load balancer in Scaleway infrastructure?

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#276]
Since November 2023, we pay Scaleway about 70€ per month for a "network" thing. This was not present before November 2023.

The corresponding resource seems to be https://console.scaleway.com/load-balancer/lbs/fr-par-1/135e4583-4f4b-4fc0-87ce-641f8ee33259/overview and it is related to k8s ingress nginx

This seems very closely related to https://github.com/kiwix/operations/issues/80

We probably didn't noticed it at that time, but it looks like something automatically provisioned this on our behalf.

Or did I missed something? @Popolechien did you already investigated that?

If not, we need to investigate why it is here, how useful (or useless) it is and take appropriate actions.

**Comment by benoit74** [comment]
![Uploading image.png…]()

**Comment by benoit74** [comment]
I investigated a bit and found:
- the load balancer is exposing only the `storage` node IP as backend
- the `storage` node seems to have different network setup:
  - it is the only node which has `ExternalIP` displayed in `Adresses` section when doing a describe, while other ones have `InternalIp` and `Hostname` in `Adresses` section
  - this might be linked to the fact that only this node has `--cloud-provider=external` passed to kubelet startup

**Comment by Popolechien** [comment]
@benoit74 To answer your question I did not look into this, I asked a few weeks ago why costs on Scaleway were so high and was told that since Scaleway usage wasn't traffic-related it probably always had been the same amount. Did not look further into it tbh.

**Comment by rgaudin** [comment]
Well that's unclear.

- This node was setup a long time ago
- It wasn't using this
- It has been reinstalled recently
- the `EXTERNAL-IP` is for the current, new node
- We did upgrade k8s around that time.
- I remember we saw that External IP/Internal IP thing during the setup of hetzner's

What I think could have happened is that maybe the upgrade bash script that we have in the repo did not work and we used the scaleway binary (I have a blurry memory about this but I cant say if it was at that time and on which node. Do you?). 

I see in [our doc](https://github.com/kiwix/operations/wiki/Machine-and-k8s-node-Setup#configure-k8s) that we started using it on September on other nodes and we used the August version of the tool.
Is it possible that we used the _latest_ version when upgrading on November 1st and that this version either switched to set this cloud-provider or was temporarily faulty? The doc doesn't [link](https://www.scaleway.com/en/docs/containers/kubernetes/how-to/edit-kosmos-cluster/) to the mentioned SCW procedure btw.

Obviously we dont know what the binary does exactly and it's possible that

**Comment by benoit74** [comment]
Yes, I will do it now.

**Comment by benoit74** [comment]
Removing `--cloud-provider=external` and restarting the kubelet did solved the situation around `Adresses` but that's all.

I don't recall exactly how we provisioned this new machine few weeks ago tbh, it was even before my holidays that this kubelet was configured. Maybe I copy-pasted conf from existing machine to avoid discrepancy ... tbc next time we provision a new k8s node.

Looking a bit more into scaleway documentation, it seemed quite obvious the load balancer was provisioned through a `LoadBalancer` service we had in the `deploy.yaml` we used to deploy nginx. 

I deleted the resource in k9s and it almost instantly removed the resource in Scaleway console.

No visible / noticeable impact on production so far (LB IP was not advertised anywhere in our DNS anyway ...)

I commented out corresponding resource in deploy.yaml: https://github.com/kiwix/operations/commit/0e287785f4ff57996771e3eafbef1d3dff78cf0f

So from my PoV, it is quite clear what happened:
- we did not realized when upgrading k8s cluster in November 2023 that we had deployed a new LoadBalancer resource which was really provisioning as a service on Scaleway console, with associated cost
- we did not realized that invoice had a new unsollicited section with significant associated costs

We need to be careful on this on next k8s updates / invoice reviews.

**Comment by kelson42** [comment]
I would recommend that once a quarter, there is an IT cost review with @Popolechien

**Comment by rgaudin** [comment]
Thank you @benoit74 for the detailed analysis. I'd like to point out that, as shown by [the history](https://github.com/kiwix/operations/commits/0e287785f4ff57996771e3eafbef1d3dff78cf0f/nginx-ingress/deploy.yaml), this `Service` that you removed had been there for a long while, without this behavior.

So something changed on Scaleway side. It seems the LB offer has been there for a long time but maybe they exposed it this way at some point ; I'd say [around October 2023](https://www.scaleway.com/en/blog/kubernetes-load-balancer/).

**Comment by benoit74** [comment]
This file history says that it this file and this LoadBalancer service have been deployed on 1. November 2023, exactly when the billing started to occur on the invoice, so I don't get your point.
