### ISSUE TITLE
sisyphus worker is dead

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#278]
sisyphus worker machine is declared dead by scaleway support, see https://console.online.net/fr/support/ticket/1459762

As discussed with @rgaudin ATM, we will ask them to provide identical machine asap and I will reinstall the worker.

**Comment by benoit74** [comment]
Machine has been provisioned by Scaleway at 06:53 UTC, I've started the recovery procedure.

**Comment by benoit74** [comment]
Machine is back online, pipe on zimit is obviously quite significant

I documented the restore procedure since there is some subtleties not to forget: https://github.com/kiwix/operations/wiki/Restore-Zimfarm-sisyphus-worker

@rgaudin can you please confirm you can SSH to the machine, that the configuration is OK and that procedure is correct. If everything is fine, please close the issue.

**Comment by benoit74** [comment]
For later reference, pipe when starting again the worker was at 45 tasks.

I had to cancel https://farm.zimit.kiwix.org/pipeline/e3728793-19c8-441e-8a44-db7a32a62b5a. I have no idea why this task started despite the Zimfarm manager being down for maintenance ... I suspect the update of Docker CE caused a restart of the compose stack and the Zimfarm manager restarted at that moment, immediately starting a task, just before I rebooted and "killed" the machine.

**Comment by rgaudin** [comment]
Shouldn't this be closed now?

**Comment by benoit74** [comment]
> @rgaudin can you please confirm you can SSH to the machine, that the configuration is OK and that procedure is correct. If everything is fine, please close the issue.

**Comment by rgaudin** [comment]
I confirmed on slack the other day 👍
