### ISSUE TITLE
Redirect Kiwix Wiki Content to library.kiwix.org (and stop updating from library-maint)

### ISSUE THREAD

**Issue by rgaudin** [kiwix/operations#288]
@kelson42, we are still updating https://wiki.kiwix.org/wiki/Content several times a day.

I understand this used to be a (popular?) user-friendly way to browse the Kiwix Catalog back in the days.

Now that we want library.kiwix.org to be the Catalog frontend, and given it is a lot more user-friendly and powerful, should we keep maintaining this?

Note: there is no pressing issue with it at the moment, but occasionally, something breaks and we have to spend some time to fix it.

**Comment by rgaudin** [comment]
![Image](https://github.com/user-attachments/assets/7605ff66-1bb4-489b-836b-48814560f8f5)

**Comment by kelson42** [comment]
I think we could /should redirect that page to library.kiwix.org and stops zhe update.
