### ISSUE TITLE
Wasabi files are not purged correctly in org-kiwix-zimfarm-artifacts bucket

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#291]
Default retention is 1 month, but I have found files which have been pushed here since way longer.

For instance, the artifacts of https://farm.openzim.org/pipeline/d1fa0c7a-29c2-4229-80cf-686aba6ac0f5/debug are still there.

**Comment by benoit74** [comment]
As interim action, I've added a lifecycle rule to automatically delete objects after 30 days. Not sure this is going to work.

Real issue is https://github.com/openzim/zimfarm/issues/1035

We must obviously also review bucket sizes in quarterly cost review with @Popolechien

**Comment by rgaudin** [comment]
Do you mean you added a bucket rule to automatically delete after 30d? If so, any attempt to set the auto-delete per-object under 30d will fail.

**Comment by benoit74** [comment]
I confirm that bucket is now purged of objects older than 30 days thanks to the lifecycle rule. Will need to be fixed by https://github.com/kiwix/operations/issues/293 once https://github.com/openzim/zimfarm/issues/1035 is fixed and deployed.

Closing this issue, incident is closed and problem properly tracked in dedicated issues.
