### ISSUE TITLE
Magnet download of noted.lol is not working

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#294]
I'm trying to download via magnet link noted.lol ZIM from https://library.kiwix.org/#lang=eng&q=noted

Magnet link is 

```
magnet:?
&xt=urn:btih:e74186d5df61550a1f8206f9bc01e38087ececee
&xt=urn:md5:f07bbc038357a3186ec65c304488e5ee
&xl=1380001806
&dn=noted.lol_en_all_2024-10.zim
&as=http%3A%2F%2Fdownload.kiwix.org%2Fzim%2Fzimit%2Fnoted.lol_en_all_2024-10.zim
&tr=http%3A%2F%2Ftracker.openzim.org%3A6969%2Fannounce
&tr=udp%3A%2F%2Ftracker.openzim.org%3A6969%2Fannounce%0A
&ws=http%3A%2F%2Fdownload.kiwix.org%2Fzim%2Fzimit%2Fnoted.lol_en_all_2024-10.zim
&xs=http%3A%2F%2Fdownload.kiwix.org%2Fzim%2Fzimit%2Fnoted.lol_en_all_2024-10.zim.torrent
```

Transmission stays stuck with "torrent metadata needed":

![Image](https://github.com/user-attachments/assets/8ee862c0-bc40-423e-b01d-2d62a62ab9ac)

I'm using Transmission 4.0.6 (38c164933e) on Mac OS Sonoma 14.5 (Apple Silicon).

Note that the ZIM has been very recently (yesterday) pushed to storage / published in library.

Adding to Transmission the torrent manually downloaded from `xs` attribute above works like a charm.

@rgaudin can you please have a look, I'm not that experienced with magnet links and I honestly don't get what could be wrong here

**Comment by rgaudin** [comment]
Mirrobrain's magnet


```
magnet:?xt=urn:btih:e74186d5df61550a1f8206f9bc01e38087ececee
&amp;xt=urn:md5:f07bbc038357a3186ec65c304488e5ee
&amp;xl=1380001806
&amp;dn=noted.lol_en_all_2024-10.zim
&amp;as=http://download.kiwix.org/zim/zimit/noted.lol_en_all_2024-10.zim
&amp;tr=http://tracker.openzim.org:6969/announce
&amp;tr=udp://tracker.openzim.org:6969/announce
```

**Comment by benoit74** [comment]
This is "normal", it looks like transmission is not using the `xs` parameter at all: https://github.com/transmission/transmission/issues/317 ; so it waits for peers to download metadata

**Comment by rgaudin** [comment]
Indeed, as verified with @benoit74, there are very few torrent clients that supports automatically downloading the .torrent file themselves from the the `xs` key.

This means that for them, even a webseed-able magnet is not enough if there is no peer providing the metadata. This makes #43 very important.

Clients supporting xs:

- [Tixati](https://www.tixati.com/download/) Windows, Linux (Freeware)
- [exatorrent](https://github.com/varbhat/exatorrent) CLI with Web UI macOS, Linux, Windows, Docker (GPLv3)

We did found a bug that affects qbittorrent: https://github.com/kiwix/libkiwix/issues/1157
