### ISSUE TITLE
Add donation widget to library.kiwix.org

### ISSUE THREAD

**Issue by Popolechien** [kiwix/operations#295]
Donorbox now provides a floating widget (seel right attached image, right-hand side) that redirects to our donation page:
![Image](https://github.com/user-attachments/assets/37b293e6-f11e-423a-93c3-2050b4f82e9b)

It would be nice to have it show on library.kiwix.org

Code is 
`<link rel="stylesheet" type="text/css" href="https://donorbox.org/animate-popup-donate-button.css"><script type="text/javascript" id="donorbox-donate-button-installer" src="https://donorbox.org/install-donate-button.js" data-href="https://donorbox.org/kiwix?default_interval=m" data-style="background: rgb(255, 153, 51); color: rgb(255, 255, 255); text-decoration: none; font-family: Verdana, sans-serif; display: flex; font-size: 16px; padding: 8px 22px 8px 18px; border-radius: 5px 5px 0px 0px; gap: 8px; width: fit-content; line-height: 24px; position: fixed; top: 50%; transform-origin: center center; z-index: 9999; overflow: hidden; right: 20px; transform: translate(50%, -50%) rotate(-90deg);" data-button-cta="Support" data-img-src="https://donorbox.org/images/white_logo.svg"></script><link rel="stylesheet" type="text/css" href="https://donorbox.org/animate-popup-donate-button.css"><script type="text/javascript" id="donorbox-donate-button-installer" src="https://donorbox.org/install-donate-button.js" data-href="https://donorbox.org/kiwix?default_interval=m" data-style="background: rgb(255, 153, 51); color: rgb(255, 255, 255); text-decoration: none; font-family: Verdana, sans-serif; display: flex; font-size: 16px; padding: 8px 22px 8px 18px; border-radius: 5px 5px 0px 0px; gap: 8px; width: fit-content; line-height: 24px; position: fixed; top: 50%; transform-origin: center center; z-index: 9999; overflow: hidden; right: 20px; transform: translate(50%, -50%) rotate(-90deg);" data-button-cta="Support" data-img-src="https://donorbox.org/images/white_logo.svg"></script>`

**Comment by rgaudin** [comment]
FYI this can only be displayed on the homepage, and not when reading ZIMs or in the search results.

@kelson42, are you OK?

**Comment by kelson42** [comment]
Yes, i'am. I guess via the revert-proxy?

**Comment by rgaudin** [comment]
No, neither varnish nor the nginx in front of it does content rewriting easily. See linked PR
