### ISSUE TITLE
Update Kiwix Wiki to point to library.kiwix.org

### ISSUE THREAD

**Issue by rgaudin** [kiwix/operations#298]
Following #288, https://wiki.kiwix.org/wiki/Main_Page is now outdated and should be updated to point to library.kiwix.org

I believe @kelson42 is the one with the knowledge of the template web that is this part of the Wiki.

**Comment by kelson42** [comment]
I believe to have done the work. Let me know if I have forgotten something

**Comment by rgaudin** [comment]
LGTM
