### ISSUE TITLE
Can we detect unusual traffic from China?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/operations#299]
Someone wrote : 
> At OSSPlanet we noticed some weird traffic (from China/Hong Kong) since earlier this year. Some IPs kept pulling data from our servers, repeatedly downloading the same batch of huge files, and trying to drain our resources.

We don't really have datapoints before August I believe, but is there anyway to figure out if we're dealing with the same pattern?

**Comment by rgaudin** [comment]
The only information we have is what's on stats.kiwix.org for download.kiwix.org.

**Comment by Popolechien** [comment]
Ok, nothing unusual from what I can see. Closing ticket, thanks for the quick turnaround.
