### ISSUE TITLE
Simplify/enhance procedure to delete a ZIM

### ISSUE THREAD

**Issue by benoit74** [kiwix/operations#307]
Currently, the procedure to delete a ZIM is a bit complex / long:
- we first need to put the imager in maintenance, ensuring there is no running job
- then we delete the file
- then we regenerate the library
- then we restore imager operations

This has multiple drawbacks:
- waiting for no running job on the imager is painful, and we hope it is going to be more and more rare that the imager is "free"
- putting the imager in maintenance everytime we need to delete a ZIM is not very good for our users
- we are at risk of forgetting (at least for some hours) to restore imager operations and having an imager in maintenance for too long
- there is a slack time (currently quite small, but still) between the moment where the file is deleted and the moment the library is updated where the file is still listed in the library but not available anymore on the disk, leading to weird effects in the library (especially since we have varnish cache in front)

I propose that we enhance the library generation script to ignore ZIM file which have a delete marker right away. The delete marker can for instance be a file name like the ZIM but with a `.deleted` suffix. I.e if I want to remove `physicell_en_all_maxi_2023-01.zim` from the library, I just `physicell_en_all_maxi_2023-01.zim.deleted` on the filesystem and relaunch library generation job. Once library is regenerated and no more imager job are using this file, I can remove both files from the storage. This would allow to not put into maintenance at all, and never have a library with files which are in fact gone.

WDYT?

**Comment by rgaudin** [comment]
👍
